### ISSUE TITLE
Atomic `Polygon` model

### ISSUE THREAD

**Issue by amaurymartiny** [chronhq/backend#1]
_From @amaurymartiny on October 10, 2018 22:27_

Proposed by @wtokumaru in #26:

> Can we separate the geojson data from the Territory and have it as a separate Polygon (or whatever) Entity that different territories can point to (like how they point to a Nation/PoliticalEntity)? We need this in order to avoid having like 20 Belaruses or Romes or Alsace-Loraines. Even the notion of a territory being something that trades hands or an administrative border/subdividision retained between social changes inherently can not be not limited to a single continuous time range...

This model would have the following fields:
- id
- name
- geometry (geojson field)
- references

I personally like this idea. I had in mind to create a new Territory each time a PoliticalEntity changes borders, thinking that some geojson will be duplicate, but it's okay b/c db storage is cheap. But if we want a clean solution, this is definitely the way to go.

We will create a small collection of all known atomic territories, and future mappers can just pick&assemble them to build Territories.

Note: This corresponds exactly to CIDOC's http://www.cidoc-crm.org/Entity/E94-Space-Primitive/Version-6.2.

---

Problems:

1. Once we have a small collection of Polygons, how to efficiently search through them?
    - We'll have a `name` field, but it can be duplicate, is not precise etc...
    - If the search algorithm is not performant, mappers will create duplicate polygons, and we'll have polygons that are 99% similar.
2. If I want to create the Territory of France today in 2018, probably I'll find the Polygons of the 101 departments in our collection. So UX-wise, I basically need to search/click on 101 items? (possibly more, if the department is not the most atomic polygon)

_Copied from original issue: chronoscio/backend#53_

**Comment by MiklerGM** [comment]
My thoughts about _atomic polygons_ 
It's a good idea that allows us to solve some problems with merging maps across years. But it's very expensive to add a new border (this is what you usually do).

Main drawback of this proposal is extremely large data overhead for client to download.

This approach is not easy to combine with _vector tiles_.

Using _SpacePrimitives_ without any duplication data makes it almost impossible to draw additional layers.  If the _City_ was grown and you wan't to extend it's borders. Drawing additional layer of religion expansion are also impossible.

By my calculations this approach will not save client's bandwidth. 
You still need to load the whole world map no matter what, but now with tons of additional useless inner borders. It would be possible not to fetch any additional data after changing year, but it will cost us lots of RAM (it's not suitable for mobile devices)

Right now we don't have any UX for mappers in our roadmap (for 3-5 months it's not a top priority). About which kind of UI you are talking about?

In Chronist we were storing geodata separately from props for the same reasons - avoid duplicated data. We've been storing each unique territory and combine it with right props on demand.

We've been using ShapeFiles (one per year for the whole world) with all necessary data in dbf as a buffer between mappers and database.  
It's also not suitable for using it with vector tiles magic

**Comment by MiklerGM** [comment]
Thinking about _atomic polygons_ from a different perspective.

We can create a list of atomic polygons from shp files. It can be done with python bindings for GIS software.
Each mapper will be able to download shapefile with all _atomic polygons_ and edit it in his own copy of QGIS/ArgGIS.

**Comment by MiklerGM** [comment]
I was wondering how our map will look if we draw every territory border. 
Keep in mind it's simplified maps, we keep only 5% of all the data. We did not split countries into regions (amount of maps would be multiplied).
![image](https://user-images.githubusercontent.com/61106/47958052-4ab82900-dfc3-11e8-8154-2f925e0bbc95.png)
![image](https://user-images.githubusercontent.com/61106/47958060-6cb1ab80-dfc3-11e8-848f-e9d5d8705dce.png)

**Comment by amaurymartiny** [comment]
Replaced with #11, cf the model structure there
