### ISSUE TITLE
Update map position marker for narratives

### ISSUE THREAD

**Issue by MiklerGM** [chronhq/backend#111]
According to new UI draft Map Settings and Narration models should be updated
- bbox is no longer needed in Map Settings
- center(pin) point should be added to Narration
```python
# Map Settings
# [[Left, Top], [Right, Bottom]]
bbox = models.MultiPointField()
```
![image](https://user-images.githubusercontent.com/61106/55815005-e2302380-5aef-11e9-996f-324348090e95.png)
![image](https://user-images.githubusercontent.com/61106/55815081-04c23c80-5af0-11e9-8de0-902b9cfaea23.png)

**Comment by ataalik** [comment]
Do we need any constraints on narration center ?

**Comment by MiklerGM** [comment]
I don't think we have any, it's just a position of a special `pin` with
text and a point where we fly to

чт, 18 апр. 2019 г. в 09:27, Ata Ali Kılıçlı <notifications@github.com>:
