### ISSUE TITLE
Fetch list of STVs

### ISSUE THREAD

**Issue by faultcore** [chronhq/backend#114]
For the user panel, we'll need a new endpoint to get a list of STVs without geometry for specific TE.
And another endpoint that returns shapefile of geoJSON for selected STV with an option to also return direct political relations.

**Comment by whirish** [comment]
I would rather not create new endpoints, do we want nested STV data -geometry for the first? I think it currently does this but with a list of IDs. Also, it might be better to generate shapefile on the frontend from geojson returned by the backend.

**Comment by MiklerGM** [comment]
Oh, it's a good idea to use nested data for TE query, that will solve first three tasks
- Get TE by entity_id
- Search by wikidata_id + entity_label + entity_id
- Get list of STVs without geometry for selected TE

It is probably not a good idea to generate shapefile on the frontend
- it's a binary format, i'll need additional libraries for that
- double mem usage - fetch geojson, convert to shp, create blob, give the link
- it can be easily generated by postgis

We can forget about shp files and use the geojson instead.

Can we do temporary links to fetch geojson directly from the backend?

**Comment by whirish** [comment]
> Can we do temporary links to fetch geojson directly from the backend?

Now that we've removed APs I believe this is solved through the `/spacetime-volumes/<pk>/` territory property.
