### ISSUE TITLE
Sort Start and End year in narrative

### ISSUE THREAD

**Issue by MiklerGM** [chronhq/backend#119]
I've created a dummy narrative for api test purposes and noticed, that `start_year` can be larger than `end_year`.
As one of the options we could change that and return the minimum and maximum dates in Julian Date format

I have also noticed that we are using reserved word **order** for column name in narrations. It means that you can not write any query for this field. This will not work :-(
```sql
UPDATE api_narration SET order = 1 WHERE id = 3;
```
---
API response
```json
[{ 
 "id":1,
  "start_year":1800,
  "end_year":1781,
  "author":"author",
  "title":"Title",
  "url":"penguin",
  "description":"Story about fabulous penguin",
  "tags":["conflict","test"]
}]
```

SQL to reproduce, third narration has smaller date than first one
```sql
SELECT * FROM api_narrative;
INSERT INTO api_narrative values (
	1, 'author', 'Title', 'penguin', 'Story about fabulous penguin', ARRAY['conflict', 'test']
);
SELECT * FROM api_mapsettings;
INSERT INTO api_mapsettings values (1, 1, 8);
SELECT * from api_narration;
INSERT INTO api_narration values (
  	1, 1,
  	'Narration Title 1',
  	'Narration description long long long',
  	'Monday', null, null, 1, 1,
  	2378587,
  	ST_GeomFromText('POINT(-71.060316 48.432044)', 4326));
					
  INSERT INTO api_narration values (
  	2, 2,
  	'Lorafadf adsf',
  	'Narration description long long long',
  	'1337', null, null, 1, 1,
  	2378987,
  	ST_GeomFromText('POINT(-41.060316 8.432044)', 4326));
					
  INSERT INTO api_narration values (
  	3, 3,
  	'Treg s ss adsf',
  	'Narration description long long long',
  	'1337', null, null, 1, 1,
  	2371587,
  	ST_GeomFromText('POINT(-1.060316 8.432044)', 4326));

 SELECT *,
 EXTRACT(year from TO_DATE(TO_CHAR(map_datetime, '9999999999.9'), 'J')) as year
 from api_narration;
```

**Comment by whirish** [comment]
That is done by the django ordered model package, we should probably log a ticket there  https://github.com/bfirsh/django-ordered-model

**Comment by whirish** [comment]
I have logged https://github.com/bfirsh/django-ordered-model/issues/197. Issue tracker seems a bit dead so I'm not expecting a response anytime soon. In the meantime, it looks like included a bracket around a reserved column name will work? `UPDATE api_narration SET [order] = 1 WHERE id = 3;`

**Comment by MiklerGM** [comment]
Double Quotes will solve the problem with reserved words

https://stackoverflow.com/questions/7651417/escaping-keyword-like-column-names-in-postgres
