### ISSUE TITLE
Generate docs for backend models

### ISSUE THREAD

**Issue by amaurymartiny** [chronhq/backend#14]
Is it possible to generate them nicely? Like a class diagram or something like that?

**Comment by whirish** [comment]
The Django admin has a [documentation generator](https://nearsoft.com/blog/the-secret-of-django-auto-generated-admin-docs/), or we could try something with Sphinx [autodoc](https://medium.com/@eikonomega/getting-started-with-sphinx-autodoc-part-1-2cebbbca5365) which might be a bit more advanced.
