### ISSUE TITLE
Fix Makefile to be more gentle for other containers

### ISSUE THREAD

**Issue by MiklerGM** [chronhq/backend#179]
I've been avoiding this for quite sometime, and finally this thing got me. I've removed everything on one node.

https://github.com/chronhq/backend/blob/master/Makefile#L34-L36

That is a very bad combination especially with
https://github.com/chronhq/backend/blob/master/Makefile#L20

**Comment by whirish** [comment]
I would propose to just remove this command. I haven't encountered any cases for using it in place of `make clean`.

**Comment by MiklerGM** [comment]
Good for me
