### ISSUE TITLE
GraphDB data-schema discussion 

### ISSUE THREAD

**Issue by v1kun** [chronhq/backend#2]
So Me and @MiklerGM discussed a bit.
We suggest use Neo4j graphDB for our non-spacial data . Let's begin with Narratives.

*Narratives* is a story from someone about some events from Author's point of view

*Narratives | Stories | Courses*
PROPERTIES
_CreatedBy_ // Author // FKEY
MapCoordinates // For camera position
MapZoom // For camera position
Description // Some text what is this story about
Title // A title
FromYear // 1st year of "story"
ToYear //last year (mb usefull for building ui)
language // lang of narrative
health // computed field based on fact rating
rating //
MapBoxStyle // Link or relation to specific map style using mapbox api
RELATIONS
_hasTimeline_ // relation to special list of events and texts
_hasTags_ // for search (Europe, strict language)

Every Narrative can have one or several timelines (just as in Chronist/Ainu)

*Timeline | Storyline*
PROPERTIES
[List of *FactInterpetations* in proper order to display]
RELATIONS
_hasTicks_

Timeline holds several *FactInterpretation* s

*NarrativeText | FactInterpretation*
PROPERTIES
text // text of
header // or title
date // displayed date
RELATIONS
_basedOnFacts_

*FactInterpretation* s  should be bases on facts that we have, has ratings and so on.

Here is small graph representing the idea
[123]https://puu.sh/BV3sS/1751e110b7.png(url)

**Comment by amaurymartiny** [comment]
Some remarks.

1. Do we put facts and narratives in the same DB? Two concerns I have:
- Facts will be the in open database (e.g. CC licence), whereas narratives will probably not be (if we want to have protected narratives).
- Facts are really suitable for graph db. However, narratives are simple enough to be structured in RDBMS (cf `FKEY` that you wrote above).

This is an open question, I'm still okay with everything in one DB. Though I prefer 2 DBs for clarity.

2. In your picture, the `E69_Death`'s description should be "Death of Kennedy", and not the date. Following CIDOC geo, the way to model this is: https://docs.google.com/document/d/1yYXFWKdT6G03K7Kq-iAY6I98b-niE1SiboyLeH8HZjM/edit#


General idea:
- an event/political entity has a lot of phenomenal spacetime volumes, which describes its evolution
- each PSTV has a spatial projection, and a time projection
- we approximate these projections with declarative values (i.e. geojson for space, ISO date format for date)
- ([reference](http://new.cidoc-crm.org/crmgeo/sites/default/files/CRMgeo1_2.pdf))

Note: this seems complicated, but I'll put tomorrow in that gdoc examples of why it's needed.

3. Can you explain why a narrative has multiple timelines? Are all timelines created by the same author?

4. `has_source` bothers me a bit. For example, for the entity "The Mongol Empire" or "Napoleon", what sources do they have? Full books on them seem a bit vague to me.

Another problem: "Death of X" might have 2 sources, one that is very reliable on the location of the death, and another that is very reliable on the exact time of the death. Would you say this Event has 2 sources? How can you figure out if the source was talking about the location or time of the event?

I propose 2 solutions (still not sure which one is better):
- this one. We can also use `P70_Documents` in this case.
- to not put sources on entities, but on properties (i.e. edges). Source is not a node, nor a link, but a meta-information on a link (so not in the graph db itself). So the Event "Death of Kennedy" does not have a source. But the link (`Q11` in the gdoc) which says "The spatial projection of PSTV of death of kennedy has value POINT([39, 12])" has a source.

5. Source is just a node for now. 
a. we can either use it like this, and use some predefined format (like Wikipedia's citations) to parse the sources.
b. or we define a system of nodes/edges for sources too, like `author has_many books` `book has_many chapters` etc to organize this, and e.g. facts can reference a special chapter. (Note: CIDOC is probably good for organizing this type of data too).

Imo I think 2 will be too much, I propose we start with a.

**Comment by MiklerGM** [comment]
> Can you explain why a narrative has multiple timelines? Are all timelines created by the same author?

It's more like an over engineering issue. It was proposed based on idea, that you can extends or encapsulate someones story (timeline) 

For e.g. we have small narrative about building new sewage treatment facilities
Other user extending this narrative by adding some events, that were a reason of this renovation (Neighbor country was angry about pollution)

Maybe these relations should be done from different place e.g **NarrativeText** hasLink to a narrative

**Comment by v1kun** [comment]
1. MAIN idea of using GraphDB is keeping everything connected (related), if we sepparate facts (Graph) and Narratives (RDB), we can loose in consistency. 

FKEY is for user auth, link to author profile, making auth in graph is inpractical and it's not data issue.

2. Yeah, I simplified this part on purpose. IMO using everything from CIDOR structure might be an overcomplication, because CYPHER querries might also be slightly more complex, it's just a concern. 

3. It's probable, that some narrative can have several timelines, it's was the concept when you can compare simultaneous events in different places.

4/5. That's bothers me too, it's not clear what CIDOC entities should/can have source, for instance:
Existance of JFK -  no.
Date of birth of JFK - certanly. 
So, by "sourcing" his death we confirm his existence.
Let's assume, there is a some historical person, for example, Homer (author of the Iliad and the Odyssey). Should we corfirm by some document his existence? I think so. 
So, yes, it's vague.

Please, do not mix, Properties (features of Nodes/Vertices) and Edges/Relations.

Should sources be Nodes or its property:?
Pretty sure, It's a Node with properties like:
- type of source (is it a book, a paper or a manuscript)
- year of publishing/discovery
and so on. So that we can extract this features easily.

**Comment by MiklerGM** [comment]
>Facts will be the in open database (e.g. CC licence), whereas narratives will probably not be (if we want to have protected narratives).

Can you explain, how you see it? I don't get it, why we can't have single db for data with different licenses. Or you think we should share a **.sql** file with all of our data?
We can add additional restrictions for read/write permissions. In the future we will have an UI, with users and their roles.
If we are discussing a data sharing process with someone from different company, we can build an API instead of publishing db connector to the public.

**Comment by amaurymartiny** [comment]
A first draft of the db spec has been detailed here: https://docs.google.com/document/d/11IcArltvRz-du0ewBR54NQlXNdfqextR4d-l_1GTce8/edit#

We can start implementing it, closing this issue. If there are more issues are db arch, please open more specific issues.
