### ISSUE TITLE
Fit names in territorial bounds

### ISSUE THREAD

**Issue by faultcore** [chronhq/backend#21]
Right now we have a blind map, country names are available only in balloon with mouse on hover. 
<img width="759" alt="2018-12-02 12 35 38" src="https://user-images.githubusercontent.com/156677/50160470-bd623700-02d9-11e9-9293-227609cae971.png">
The more info we get, the bigger and more unusable that balloon will become. One of obvious proposals is to create an MVT layer with country names (like in Europa Universalis or any paper maps). Same naming can be applied later to different admin_level
![](https://i.redd.it/5n556z8xrl321.png)
[Reddit post](https://www.reddit.com/comments/a54sko)
**Describe the algorithm suitable for generating names with similar behavior.**

**Comment by whirish** [comment]
I remember reading [a reddit post](https://www.reddit.com/r/paradoxplaza/comments/2jcf2x/how_do_paradox_games_perfectly_paint_nation_names/clb2rsr/) from the eu4 devs on this a while ago. A modified version of [ST_LongestLine](http://postgis.net/docs/ST_LongestLine.html) might be worth looking into as well.

**Comment by ataalik** [comment]
Aren't these a bit overkill. For example in google maps the names of the countries are always at the middle point. And they are in similar font sizes on different zoom levels. Wouldn't that be easier and familiar. 
An advantage of using an approach similar to Paradox's one would be country names following the viewport of the map. I.e. with a static approach like choosing the middle of the polygon or the longest line of the whole polygon once you can view only the western side of the Russia it's name would be outside of the viewport, unlike the paradox games and the map given above.

**Comment by MiklerGM** [comment]
@ataalik you right, using same algorithm is an overkill. Simple names on map would be enough.

I check google maps and I spot some interesting facts:
They have different font sizes for different countries.
Font size changes along with zoom
They are dynamically deciding what they are showing (because of their map projection)
Country names never overlapping any major cities, as a result country names are not usually in the center or on a longest line

**Comment by faultcore** [comment]
<img width="880" alt="2019-01-16 17 43 17" src="https://user-images.githubusercontent.com/156677/51280902-2fb15e80-19e1-11e9-9fd4-2d9c31607fec.png">
I've also noticed this one and it looks very nice. However no cities without zoom. Maybe it's a good idea also?

**Comment by whirish** [comment]
I believe we concluded on the last call that this would be a frontend task?

**Comment by whirish** [comment]
That's what I thought as well, I'll try and look into a PostGIS solution

**Comment by MiklerGM** [comment]
If we want to add labels using mapbox we should serve labels (text) in MVT.

**Comment by whirish** [comment]
@MiklerGM could you link a documentation page or example showing how to serve MVT with text?

**Comment by MiklerGM** [comment]
@whirish we are serving cities like this already.
It's a geo point + text label

**Comment by MiklerGM** [comment]
This is how it works on frontend (MVT Style for cities)
https://github.com/chronhq/frontend/blob/78cf7fc47b010a29d19072170e1fc4bde93a99a2/src/models/MVTStyles/CitiesMVTStyle.js#L63

**Comment by whirish** [comment]
Ah, so it's rendered on the frontend and just the text is returned in the MVT. I thought the text was being rendered on the backend, got it.

**Comment by MiklerGM** [comment]
We can automatically fill the visual center by using [P625 Coordinate Location](https://www.wikidata.org/wiki/Property:P625) or [P5140 Coordinates of Geographic Center](https://www.wikidata.org/wiki/Property:P5140) from wikidata.

https://github.com/chronhq/data/issues/3

**Comment by whirish** [comment]
Nice catch, do we want to add a script in microservices to do that?

**Comment by MiklerGM** [comment]
We need to do this only once for whole db, I am not sure we need a microservice for that.

Probably I would do it as part of admin interface.

**Comment by MiklerGM** [comment]
Next query will set the visual center as a centroid of the largest polygon or point on the surface if the centroid is outside of the polygon
```
UPDATE api_spacetimevolume SET visual_center = foo.visual_center FROM (
  SELECT *, CASE WHEN ST_Intersects(geom, centroid) IS true THEN centroid ELSE surface END AS visual_center FROM (
    SELECT id, geom, ST_Centroid(geom) as centroid, ST_PointOnSurface(geom) as surface FROM (
      SELECT id, geom FROM (
        SELECT *,
          (MAX(ST_Area(geom)) OVER (PARTITION BY id) = ST_Area(geom)) as sqft
          FROM (
            SELECT id, (ST_Dump(territory)).geom AS geom
            FROM api_spacetimevolume
          ) as foo
      ) as foo
      WHERE sqft = true
    ) as foo
  ) as foo
) as foo
WHERE foo.id = api_spacetimevolume.id;
```

**Comment by faultcore** [comment]
Added central point to TE. A label is placed based on that point.
