### ISSUE TITLE
How to track historical edits of a graph db node/edge?

### ISSUE THREAD

**Issue by amaurymartiny** [chronhq/backend#3]
All modifications of nodes and edges in the graphdb should be logged. Ideally, we could use a plugin for this.

**Comment by MiklerGM** [comment]
For logging purpose we can use insert only database and store each update, create or delete.

If we want be able to interact with old data, we should think about something else
I am not sure, that this plugin is still working, if it's not then it's a problem
https://github.com/dmontag/neo4j-versioning

btw online (without switching off the db) backup tool is only available for neo4j enterprise edition

https://iansrobinson.com/2014/05/13/time-based-versioned-graphs/
https://neo4j.com/blog/recap-intro-to-graph-databases-webinar-series-1/ (picture from this intro)
![image](https://user-images.githubusercontent.com/61106/48025261-31d68180-e143-11e8-840b-3117aa110416.png)

**Comment by whirish** [comment]
Yeah, its looking like we'll have to implement this manually.

**Comment by amaurymartiny** [comment]
So in a separate table in the RDB, where we log everything.

`| user_id | action | node_or_edge_id`
` user1        added           123`

Any better ideas?

**Comment by amaurymartiny** [comment]
Not relevant anymore.
