### ISSUE TITLE
STV updating routine

### ISSUE THREAD

**Issue by MiklerGM** [chronhq/backend#48]
Post MVP,  this could be a piece of important documentation #20

Eventually we would update our maps and we need an interface for that. Rebuilding everything from scratch requires up to a week of processing time on single thread. Even with multi threaded approach we would suffer from long execution time and lack of valuable check and highlighted difference.

In this issue I propose to describe algorithms of updating APs and STVs.
We also should describe the valuable output with changes for mappers.

What checks and validations should be performed during creation or modification of STV.

**Comment by v1kun** [comment]
So, if somehow we get an STV with wikidata_id and timestamp from mapper, e.g. (geom, Q145, 1830)
we need to:
- check in wikidata if this entity was present in this year (wikidata api);
- check if geometry is valid (postGIS);
- check if this geometry is covered by existing AP, 
  - if not - create new ones and partialy remap existing STVs (postGIS);
  - if yes - look up STVs, if new one can be added as continuation of any;

**Comment by whirish** [comment]
@v1kun this looks fine to me. I suppose the question now would be a proper implementation of the last step, which could potentially be a huge operation...

**Comment by MiklerGM** [comment]
> * check in wikidata if this entity was present in this year (wikidata api);

What do we do if it is not present? 

As an example: we have some problems with Poland:
Q36 has same date of inception as Q207272

[Q207272](https://www.wikidata.org/wiki/Q207272) (SPE 1918-1938) is a predecessor for: Q156111
[Q156111](https://www.wikidata.org/wiki/Q156111) (RPGG 1939-1945) is a predecessor for: [Q36](https://www.wikidata.org/wiki/Q36)
~Q36 (Poland 11 November 1918 - now )_// according to wikidata_
Q36 (1945 - today)

That was in our slack [here](https://chronhq.slack.com/archives/CDMV5K3M2/p1543240073017100?thread_ts=1543217496.008500)

---
> * check if geometry is valid (postGIS);

What about overlapping issues? That might be one of the biggest problems, white spaces and overlapping

> * check if this geometry is covered by existing AP,
>   * if not - create new ones and partially remap existing STVs (postGIS);
>   * if yes - look up STVs, if new one can be added as continuation of any;

if we are changing amount of APs what do we do next?
Do we update STVs APs recursively?

_Example: Shrinking territory_
We updated STV for Poland (1945-1950) by splitting `AP-7` into `AP-8` and `AP-9`. AP-9 was removed from Poland's possession.
* Mark `AP-9` (1945-1950) as a new white space
* We are updating every STV except Poland with `AP-7` to match `AP-8` and `AP-9`
* Ask user about updating Poland recursively (Remove `AP-9` from Poland if it is part of a border).

_Example: Extending territory_
We updated STV for France by splitting `AP-12` previously owned by Italy into `AP-13` (France) and `AP-14` (Italy).
* Update add `AP-13` and  `AP-14` instead of `AP-12` for every STV  except France and Italy
* Highlight overlapping territories
* Find all conflicted time periods and areas
...do something

I am out of inspiration...

**Comment by MiklerGM** [comment]
AP will be dropped soon #97 
My previous post was based on AP

**Comment by MiklerGM** [comment]
I'll write a quick update in here.

We are not inserting the predecessors, at least right now. We'll keep it simple.

- User uploads a new geometry
- User checks the overlaps #152 
- Backend is calculating new geometry
- At some point of time new information will be processed as MVT

**Comment by faultcore** [comment]
Done
