### ISSUE TITLE
Return min/max dates for Narrative

### ISSUE THREAD

**Issue by whirish** [chronhq/backend#54]
at REST endpoint

**Comment by MiklerGM** [comment]
If it is possible I would also like to have the date of the first event (not necessary the smallest date)

**Comment by MiklerGM** [comment]
I propose to add a unique `url` field for narratives.

**Comment by whirish** [comment]
I think after we add filtering narrations by narrative, the projection and settings could be retrieved from that, to avoid returning excessive data from the narratives endpoint.
Since min/max is used in the sidebar I'll have that returned in /narratives though.

What would the url field link to?

**Comment by MiklerGM** [comment]
The url would link to this exact narrative
Localhost/url

in the example above with `url = demo` we can access this narrative by visiting `localhost/demo`
