### ISSUE TITLE
Update ranking algorithm

### ISSUE THREAD

**Issue by MiklerGM** [chronhq/backend#77]
Original idea was introduced in #8 and implemented in #31 

As a result of the multiplying algorithm we got ~50% items in cached data with `rank = 0` and to improve the results we could try next proposal:

> Yeah, normalization would be nice. 
> Some simple methods like Z-Score or Minmax approach could work, but still they'll based on our multiplication, and it's not nice.
> Instead of it, I'd use some linear combination (a * x1+b * x2+c * x3), where x1,x2,x3  are number of links, a,b,c - some weights, so 0-values won't bother us.
> 

_Originally posted by @v1kun in https://github.com/chronhq/backend/pull/31_

---
- [ ] Find optimal values for weights
- [ ] implement
- [ ] Compare the results before and after (zero values, top ranked items)

**Comment by MiklerGM** [comment]
I have removed all the duplicates in api_cacheddata from duplicated items #75 
```sql
DELETE  FROM
    api_cacheddata a
        USING api_cacheddata b
WHERE
    a.id > b.id
    AND a.wikidata_id = b.wikidata_id
    AND a.event_type = b.event_type;
```
when | total items | rank = 0
-- | -- | --
Before | 5014 | 2758
After | 1532 | 921 

2/3 of all items does not have rank

**Comment by v1kun** [comment]
I guess, replacing multiplication to sum can make difference, surely, we can add weight, but imho they wont affect much

**Comment by MiklerGM** [comment]
Ranking algorithm was set to `a + b + c` in #96.
It has an acceptable results for now.
