### ISSUE TITLE
Rank data given by Wikidata

### ISSUE THREAD

**Issue by amaurymartiny** [chronhq/backend#8]
On the global 4d map, we definitely do not want to show all data explicitly (like running reality).

Ideal solution: rank data by "popularity", which in code means e.g. by PageRank. And show the 20 top popular data points in the current bounding box.

See:
- https://stackoverflow.com/questions/39438022/wikidata-results-sorted-by-something-similar-to-a-pagerank
- https://www.wikidata.org/wiki/Wikidata:SPARQL_query_service/queries/examples#Universities_ranked_by_PageRank_on_English_Wikipedia_(federated_query)

Fallback solution:
- clusters https://www.mapbox.com/mapbox-gl-js/example/cluster/

**Comment by MiklerGM** [comment]
Are you sure it's a backend task? Right now we are querying wikidata from the frontend.

**Comment by amaurymartiny** [comment]
As per the stackoverflow answer, there are 4 metrics we can use
- incoming statements
- sitelinks
- outgoing statements
- pagerank

And according to his data, these 4 are correlated. Since pagerank uses an external service, it might take too much time for our queries; but the 3 other are easy to fetch.

I propose, for simplicity, we define the rank as:
```
incoming_statements * sitelinks * outgoing_statements
```

And we store this rank in our cache table, which will have the fields:
- wikidata_id
- lat/lng
- datetime
- rank
