### ISSUE TITLE
Add model for user votes on Narratives

### ISSUE THREAD

**Issue by MiklerGM** [chronhq/backend#89]
To add a voting on narratives we should create a new model to keep track of votes

As a proposal we can store it like this

date | narrative_id | vote 
-- | -- | --
2019-03-04 12:12 | 1 | true (or 1/-1)

Computed rank should be present in narrative

**Comment by faultcore** [comment]
As discussed today: voting is enabled only for authorized users.
> We store voteinfo in users table as json and calculate overall every time someone vote and store it in narrative info.
For the start, it's ok, if we go further, imo, we can use ranking algorithm like reddit's one, when rating is calculated on freshness of +\-, but not just of overall rank. @v1kun

**Comment by whirish** [comment]
Superseded by #102
