### ISSUE TITLE
Revise Political Relations

### ISSUE THREAD

**Issue by MiklerGM** [chronhq/backend#90]
According to #38 we have direct, indirect, group types of relations

They can be combined in some ways described here
https://github.com/chronhq/wiki/blob/master/documentation/political_relations.md

How should relations for condominiums look like

**Comment by MiklerGM** [comment]
@bapo224 give us some feedback and update on this one

**Comment by bapo224** [comment]
I think the way relations combine relies too much wikidata, outside of Europe most entities don't have a wikidata entry and even the ones that do are often incomplete. You should allow mappers to enter more info directly into the site.

I also don't really understand what the 'direct' relation entails, we aren't mapping administrative subdivisions (yet) so what would be an example that it's used on? Only occupied territory?

As for condominiums, I haven't personally dealt with them so I'll ask Turnt to elaborate. I would imagine it needing multiple direct or indirect relations.

**Comment by whirish** [comment]
I will say that a key reason we decided to go with wikidata was that data can be added easily. Amaury was able to add some data for a missing entity without references and to my knowledge it's still up there. Maybe in the long term we could have a submission form on our website to create wikidata entries to streamline the process.

**Comment by whirish** [comment]
I don't think Wikidata lists the parent entities of a condominium, and condominium is also listed as a government type. Maybe we should respect this and not give these entities a relation type (we wouldn't be able to pull this data from wd anyway), and instead just list it as a government type as we would for others.

**Comment by MiklerGM** [comment]
https://chronhq.slack.com/archives/CDMV5K3M2/p1553457184020900

- keeping same relations main types
- adding new Boolean flag for user-added entities
