### ISSUE TITLE
Date format for maps and events

### ISSUE THREAD

**Issue by MiklerGM** [chronhq/backend#93]
In our database we are storing exact dates of the events, it is working fine for positive dates but not for negative ones (same problem in python).

On the frontend we need to convert strings to date objects before compare them. For [MVT](https://github.com/chronhq/frontend/issues/55)  we can not perform this evaluation,  so we are performing filtering based on [extracted](https://github.com/chronhq/backend/pull/91) year value.

In order to increase precision of the step (currently it's a year) I propose to introduce a new date format as an integer field.

y+mmdd (yyyymmdd) as a negative or positive integer would solve the day-by-day problem.

We can think of non linear or more dimensional date encoding for B.C. dates. We probably do not need day-by-day precision for ancient times.

Requirements: 
- easy to [filter](https://docs.mapbox.com/mapbox-gl-js/style-spec)  (integer or double)
- convert back to normal date
- supported by python, postgres, es6

IMHO epoch time would be too precise for our needs.

**Comment by MiklerGM** [comment]
I am Ok with using epoch time, but I am worried about 32-bit integer problem

**Comment by whirish** [comment]
Upon closer examination it appears the postgres date type [supports 4713 BC to 5874897 AD](https://www.postgresql.org/docs/11/datatype-datetime.html) out of the box. I think this would be sufficient for us? We would need to write a custom wrapper around this to use BC dates however. The year 0 problem (it doesn't exist) is what would be the main hurdle. `(date '01-01-0001') - (date '01-01-0001 BC') = 366 days` in postgres.

**Comment by MiklerGM** [comment]
Proposed on slack by @whirish 
We could use [Julian Day Number](https://en.wikipedia.org/wiki/Julian_day) as a suitable format.
Library for python: 
https://github.com/phn/jdcal 
conversion in psql: `to_date(2455452::text,  'J')`

---

Changes in following components should be made:
- Minor changes in MVT generation.
- Microservices
- YearModel and MVT styles
- Timepanel

**Comment by whirish** [comment]
Implemented in #106 and #103
