### ISSUE TITLE
Military Symbols in narratives

### ISSUE THREAD

**Issue by MiklerGM** [chronhq/backend#94]
Expand narratives by adding new layer of data with additional information about troops and their movements.

Initial proposal:
- [ ] Expeditions and paths
- [ ] Arrows for armies movements
- [ ] Front lines

Additional wish list (feel free to add more in comments)
- Units icons
- HQ position
- ...

**Comment by MiklerGM** [comment]
For army movements we could do the GeoJSON features in shape of arrow with filled with color

**Comment by whirish** [comment]
So, for this ticket we should add blank/null columns in the narration table for:
* army movements
* expeditions
* HQ/units 

and anything else?

**Comment by MiklerGM** [comment]
I think everything can be stored in a single GeoJSON field with multiple classes inside.

**Comment by whirish** [comment]
Okay, let's go with a GeometryCollection field then

**Comment by MiklerGM** [comment]
Are you sure we can add any parameters to GeometryCollection?
Probably not, because it's PostGis, and to form proper GeoJSON you are usually using all columns from the table, not only the geometry one.
https://postgis.net/workshops/postgis-intro/geometries.html

**Comment by MiklerGM** [comment]
Or we can add a table for One to Many relations. From Narration to Symbols.

In this case, columns that needed are like
`narration_id*`, `geometry_collection*`, `sprite`, `type*`, `label*`, `fill_color`, `stroke_color`, `...`, `options`

If you want to do in RDB way we need to describe a style for every feature layer before we got further.

**Comment by whirish** [comment]
I was thinking about an o2m relation, that might be a cleaner option. Or, maybe we could consider storing the collections in a JSONField, and validate it through a DRF serializer. 

The simplestyle spec outlines these parameters for geojson styles:
```
"stroke": "#555555",
"stroke-opacity": 1.0,
"stroke-width": 2,
"fill": "#555555",
"fill-opacity": 0.5
```

**Comment by MiklerGM** [comment]
We also need `type*` and `sprite` options.

- type or class is needed for me to determine which style to apply. I can use one MVT or GeoJSON as a source for multiple layers with different decorations.
- Sprite-name for special icons in our sprite files. (optional)
As Abraxis mentioned on discord, we probably need some fancy lines and it can be done by using [paint-line-pattern](https://media.discordapp.net/attachments/557215501756137494/570233836953403418/unknown.png?width=1130&height=591) and sprite images
![img](https://media.discordapp.net/attachments/557215501756137494/570233836953403418/unknown.png?width=1130&height=591)

**Comment by whirish** [comment]
We have agreed on Slack to store all extra geometries in a JSONField containing a FeatureCollection. This is to ensure geometries' properties are preserved. Serialization in the API should confirm geometries are stored in this new field.

**Comment by whirish** [comment]
Maybe it would make sense to store some symbols in the global narrative? For example front lines, I can imagine this being of use to multiple narratives. Then we can have a `Narration` > `Symbol` m2m relationship in the db.

**Comment by MiklerGM** [comment]
[adsfgsadgWDEWGGWGw.zip](https://github.com/chronhq/backend/files/3413996/adsfgsadgWDEWGGWGw.zip)
Example shapefile for testing testing additional borders in narratives
![image](https://user-images.githubusercontent.com/61106/61584221-44171500-ab44-11e9-95e5-35c1b768c105.png)
