### ISSUE TITLE
Drop Atomic Polygons

### ISSUE THREAD

**Issue by whirish** [chronhq/backend#97]
As per Slack discussion, APs will be dropped and the geometry field will instead be moved to the STV model. This is being done to save resources/processing time and we don't envision storage space becoming too much of an issue.

**Comment by whirish** [comment]
I just had a thought. The storage space needed for the db will increase exponentially if we store revision history of geometry and my calculations may not be accurate. Perhaps we should discuss how we plan to do this.

**Comment by MiklerGM** [comment]
I suggested to start using history on geometry in order to prevent acts of vandalism.
The main goal is to be able to compare and revert changes. We probably have no desire to store every change.
We might want to add some post-moderation to this process.

**Comment by whirish** [comment]
For now, should we store the last N revisions? I think 10 is probably a reasonable number while we're still small.

**Comment by MiklerGM** [comment]
Can it be cleaned with special request?

**Comment by whirish** [comment]
Not in the API yet. In the ORM to clear history past N days we would use `Model.history.filter(history_date__lt=timezone.now() - timedelta(days=90)).delete()`

**Comment by whirish** [comment]
Closed via #121
